management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
spring:
  main:
    allow-circular-references: true
  flyway:
    enabled: false
    check-location: false
    baselineOnMigrate: true
  datasource:
    url: 'jdbc:postgresql://localhost:5000/hapi_dstu3'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
  batch:
    job:
      enabled: false
hapi:
  fhir:
    openapi_enabled: true
    fhir_version: R4
    server_address:  http://localhost:8080/fhir
    defer_indexing_for_codesystems_of_size: 101
    install_transitive_ig_dependencies: true
    advanced_lucene_indexing: false
    enforce_referential_integrity_on_delete: false
    enforce_referential_integrity_on_write: false
    mdm_enabled: false
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester:
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
    subscription:
      email:
        from: test@unicia.co
        host: google.com
        port:
        username: admin
        password: admin
        auth:

