version: '3.7'

services:

  fhir:
    #build: .
    container_name: Unicia_hapifhir
    image: hapiproject/hapi:v5.3.0
    
    ports:
      - "8080:8080"
    
    environment:
      
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      SPRING_CONFIG_LOCATION: 'file:///config/env/application.yaml'
      
    depends_on:
      - db
    volumes:
      - ./application.yaml:/config/env/application.yaml
     

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5000:5432"

volumes:
  pgdata:

